stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: blueforest/gateway:1.0.0
      pushRemote: true
      registry: index.docker.io
timeout: 120